
import java.util.Iterator;
import javax.swing.JOptionPane;

/*
 * BSTDemoGUI.java
 *
 */

/**
 *
 * @author  leahy
 *   March 2010
 *
 * This is a driver class for testing a BinarySearchTreeADT class. This class
 * is inteded for use by COMP 139 students who are working on Lab 4
 */
public class BSTDemoGUI extends javax.swing.JFrame {
  BinarySearchTreeADT myTree = new BinarySearchTreeADT();
  String defaultDeleteString = "";

  /** Creates new form BSTDemoGUI */
  public BSTDemoGUI() {
    initComponents();
    defaultDeleteString = jTextFieldRemoveItems.getText();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jButtonStart = new javax.swing.JButton();
    jTextFieldRemoveItems = new javax.swing.JTextField();
    jButtonRemove = new javax.swing.JButton();
    jTextFieldAddItems = new javax.swing.JTextField();
    jButtonAdd = new javax.swing.JButton();
    jButtonClear = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jButtonList = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridheight = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipadx = 377;
    gridBagConstraints.ipady = 457;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(36, 15, 18, 18);
    getContentPane().add(jScrollPane1, gridBagConstraints);

    jButtonStart.setText("Start");
    jButtonStart.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonStartHandler(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.ipadx = 43;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(41, 15, 0, 0);
    getContentPane().add(jButtonStart, gridBagConstraints);

    jTextFieldRemoveItems.setText("p,q,r,s,t,u");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.ipadx = 94;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(47, 10, 0, 0);
    getContentPane().add(jTextFieldRemoveItems, gridBagConstraints);

    jButtonRemove.setText("Remove");
    jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonRemoveHandler(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.ipadx = 29;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
    getContentPane().add(jButtonRemove, gridBagConstraints);

    jTextFieldAddItems.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldAddItemsHandler(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.ipadx = 94;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(52, 10, 0, 0);
    getContentPane().add(jTextFieldAddItems, gridBagConstraints);

    jButtonAdd.setText("Add");
    jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonAddHandler(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.ipadx = 49;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
    getContentPane().add(jButtonAdd, gridBagConstraints);

    jButtonClear.setText("Clear");
    jButtonClear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonClearHandler(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.ipadx = 43;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(17, 10, 0, 0);
    getContentPane().add(jButtonClear, gridBagConstraints);

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("COMP 139 Lab4 Test Program");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 427;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(jLabel1, gridBagConstraints);

    jButtonList.setText("List");
    jButtonList.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonListActionPerformedHandler(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.ipadx = 51;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(57, 10, 0, 0);
    getContentPane().add(jButtonList, gridBagConstraints);

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-565)/2, (screenSize.height-571)/2, 565, 571);
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonClearHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearHandler
    myTree = new BinarySearchTreeADT();
    jTextArea1.setText("");
  }//GEN-LAST:event_jButtonClearHandler

  private void jTextFieldAddItemsHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddItemsHandler
    myTree.add(jTextFieldAddItems.getText()); 
    jTextArea1.setText(myTree.printTree());
    jTextFieldAddItems.setText("");
  }//GEN-LAST:event_jTextFieldAddItemsHandler
  
  private void jButtonAddHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddHandler
    java.util.StringTokenizer strTok = new java.util.StringTokenizer(jTextFieldAddItems.getText(),","); 
    while(strTok.hasMoreTokens()){
      myTree.add(strTok.nextToken());
    }
    jTextArea1.setText(myTree.printTree());
  }//GEN-LAST:event_jButtonAddHandler
  
  private void jButtonRemoveHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveHandler
    java.util.StringTokenizer strTok = new java.util.StringTokenizer(jTextFieldRemoveItems.getText(),","); 
    while(strTok.hasMoreTokens()){
      myTree.remove(strTok.nextToken());
      jTextArea1.setText(myTree.printTree());
    }
  }//GEN-LAST:event_jButtonRemoveHandler
  
  // When the start button is clicked, create a tree with the 26 letters of the alphabet.
  private void jButtonStartHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartHandler
    //remove BST (if it exists) and insert some data.
    String dataString[] = {"a", "b", "c", "d", "e", "f", "g", "h", "i", "j",
    "k", "l", "m", "n", "o", "p", "q", "r", "s", "t",
    "u", "v", "w", "x", "y", "z"};
    myTree = new BinarySearchTreeADT();
    for (int i = 0; i < 26; i++) {
      myTree.add(dataString[i]);
    }
    jTextArea1.setText(myTree.printTree());
    jTextFieldRemoveItems.setText(defaultDeleteString);
  }//GEN-LAST:event_jButtonStartHandler

  // List the elements in the tree in the order returned by the iterator
  private void jButtonListActionPerformedHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListActionPerformedHandler
    String list = "";
    Iterator iter = myTree.iterator();
    while (iter.hasNext()){
      list = list + ", " + iter.next();
    }
    if (list.length() > 2){
      list = list.substring(2);
    }
    JOptionPane.showMessageDialog(null,list);
  }//GEN-LAST:event_jButtonListActionPerformedHandler
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new BSTDemoGUI().setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAdd;
  private javax.swing.JButton jButtonClear;
  private javax.swing.JButton jButtonList;
  private javax.swing.JButton jButtonRemove;
  private javax.swing.JButton jButtonStart;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextField jTextFieldAddItems;
  private javax.swing.JTextField jTextFieldRemoveItems;
  // End of variables declaration//GEN-END:variables
  
}
